#!/bin/sh
set -f # noglob, disable wildcard

addpattern() {
	if [ -z "$FINDPATTERN" ]; then
		FINDPATTERN="-name $1";
	else
		FINDPATTERN="$FINDPATTERN -o -name $1"
	fi
}
##########
if [ "$#" = 0 ]; then
	DIR=".";
else
	DIR=$1
	shift
fi

addpattern *.c;
addpattern *.cc;
addpattern *.h;
addpattern *.cpp;
addpattern *.proto;
addpattern *.sql;
addpattern *.pls;
addpattern *.plb;
addpattern Imakefile;
addpattern *.java;
addpattern *.csh;
addpattern *.sh;
addpattern *.sql;
addpattern *.icc;
addpattern *.i;
addpattern *.pc;
addpattern *.xml;
addpattern *.groovy
addpattern *.js
addpattern *.yml
addpattern *.py

find $DIR -follow -type f -a \( $FINDPATTERN \)  $* |grep -v /\\.git/ |sed 's/ /\\ /g'
