#!/bin/sh
# This will repeat # times a command
# Examples:
# loop 2 date; will print a date twice
# loop 80 echo "-\c"; will print a line of 80 "-"
#
USAGE="Usage: frename [-h] | pattern repl file ..."

while getopts h OPTCHAR
do
	case $OPTCHAR in
	h) echo $USAGE >&2;
	   echo "renames files replacing pattern in file name" >&2
	   echo "Options:" >&2
	   echo "-h  : print usage and exit" >&2
	   exit 1;;
	?) echo $USAGE >&2;
	   exit 1;;
	esac
done
shift $(($OPTIND - 1))
if test $# -lt 3; then
	echo $USAGE >&2;
	exit 1;
fi

PATTERN=$1; shift;
REPL=$1; shift;
FILES=$*;

for FILE in $FILES; do
    NEWFILE=${FILE/$PATTERN/$REPL};
    echo $FILE "->" $NEWFILE
done
