#!/bin/sh
if [ $# -lt 1 ]; then
    echo "Usage: issueLookup ID [ID...]" >&2
    exit 1
fi
ISSUE_LIST=$*
JIRA_URL=http://tekcomms-jira.global.tektronix.net:8085
JIRA_AUTH="-u jirareadonly:jirareadonly"
HEADER="Content-Type: application/json"

TMPF=/tmp/issuelookup.$$
for ISSUE_ID in $ISSUE_LIST; do
    curl -s $JIRA_AUTH -X GET -H $HEADER $JIRA_URL/rest/api/2/issue/$ISSUE_ID > $TMPF
    SUMMARY=`python -c "import json, sys; print json.load(sys.stdin)['fields']['summary']" < $TMPF`
    STATUS=`python -c "import json, sys; print json.load(sys.stdin)['fields']['status']['name']" < $TMPF`
    echo "$ISSUE_ID: $SUMMARY"
    echo "STATUS= $STATUS"
done
