#!/bin/sh
if [ $# -lt 1 ]; then
    echo "Usage: issueLookup ID [ID...]" >&2
    exit 1
fi
ISSUE_LIST=$*
JIRA_URL=http://tekcomms-jira.global.tektronix.net:8085
JIRA_AUTH="-u jirareadonly:jirareadonly"
HEADER="Content-Type: application/json"

TMPF=/tmp/issuelookup.$$
for ISSUE_ID in $ISSUE_LIST; do
    curl -s $JIRA_AUTH -X GET -H $HEADER $JIRA_URL/rest/api/2/issue/$ISSUE_ID > $TMPF
    python -c "
import json, sys;
json_issue= json.load(sys.stdin);
print '%s: %s' % (json_issue['key'], json_issue['fields']['summary']);
print 'Status= %s' % json_issue['fields']['status']['name'];
" < $TMPF
done
rm $TMPF
