#!/bin/sh
# This will repeat # times a command
# Examples:
# loop 2 date; will print a date twice
# loop 80 echo "-\c"; will print a line of 80 "-"
#
USAGE="Usage: loop [-h] | [-b] [-p N] number command"
SLEEP_SEC="";
BACKGROUND="";

while getopts bp:h OPTCHAR
do
	case $OPTCHAR in
	h) echo $USAGE >&2;
	   echo "repeats a command a number of times." >&2
	   echo "Options:" >&2
	   echo "-b  : background" >&2
	   echo "-p N: sleep N seconds after each loop" >&2
	   echo "-h  : print usage and exit" >&2
	   exit 1;;
	b) BACKGROUND="yes";;
	p) SLEEP_SEC="$OPTARG";;
	?) echo $USAGE >&2;
	   exit 1;;
	esac
done
shift $(($OPTIND - 1))
if test $# -lt 2; then
	echo $USAGE >&2;
	exit 1;
fi
declare -i CNT
CNT=$1
if [ "$CNT" -le 0 ]; then
	echo $USAGE >&2;
	exit 1;
fi;
shift;

CMD="$*"
if [ "$SLEEP_SEC" ]; then
	CMD="$CMD ; sleep $SLEEP_SEC;"
fi

if [ "$BACKGROUND" ]; then
        for ((; CNT>0; CNT=$CNT-1 )); do
		eval $CMD &
	done;
	wait;
else
        for ((; CNT>0; CNT=$CNT-1 )); do
		eval $CMD ;
	done;
fi
