#!/bin/sh
set -x
if [ $# -lt 2 ]; then
    echo "Usage: repl pattern replacement [files]" >&2
    exit 1
fi
PATTERN=$1; shift
REPL=$1; shift

if [ $# = "0" ]; then
	sed -e "s/$PATTERN/$REPL/g" 
else
	FILES=$*
	for FILE in "$FILES"; do
		TEMPFILE=/tmp/repl_$$;
		cp $FILE $TEMPFILE
		sed -e "s/$PATTERN/$REPL/g" $TEMPFILE > $FILE;
		rm $TEMPFILE
	done
fi
